### ISSUE TITLE
Error when starting up

### ISSUE THREAD

**Issue by BGvdS** [jclarke0000/MMM-MyScoreboard#39]
I get an error about not finding the json-parse-async file 3 times when loading the MyScoreboard module.

Error: Cannot find module 'json-parse-async'

What can I do to solve this?
Sorry if I am a big noob and thanks for helping me.

```
pi@raspberrypi:~/MagicMirror $ npm run start
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> magicmirror@2.14.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[11.01.2021 17:06.16.348] [LOG]   Starting MagicMirror: v2.14.0
[11.01.2021 17:06.16.354] [LOG]   Loading config ...
[11.01.2021 17:06.16.359] [LOG]   Loading module helpers ...
[11.01.2021 17:06.16.361] [LOG]   No helper found for module: alert.
[11.01.2021 17:06.16.488] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.16.489] [LOG]   Module helper loaded: updatenotification
[11.01.2021 17:06.16.490] [LOG]   No helper found for module: clock.
[11.01.2021 17:06.16.808] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.16.808] [LOG]   Module helper loaded: MMM-CalendarWeek
[11.01.2021 17:06.16.809] [LOG]   No helper found for module: compliments.
[11.01.2021 17:06.16.810] [LOG]   No helper found for module: weather.
[11.01.2021 17:06.16.812] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.16.813] [LOG]   Module helper loaded: MMM-ATM
[11.01.2021 17:06.16.835] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.16.836] [LOG]   Module helper loaded: newsfeed
[11.01.2021 17:06.16.838] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.16.839] [LOG]   Module helper loaded: MMM-MyScoreboard
[11.01.2021 17:06.16.839] [LOG]   All module helpers loaded.
[11.01.2021 17:06.16.946] [LOG]   Starting server on port 8080 ...
[11.01.2021 17:06.16.960] [LOG]   Server started ...
[11.01.2021 17:06.16.962] [LOG]   Connecting socket for: updatenotification
[11.01.2021 17:06.16.963] [LOG]   Connecting socket for: MMM-CalendarWeek
[11.01.2021 17:06.16.963] [LOG]   Starting node helper for: MMM-CalendarWeek
[11.01.2021 17:06.16.964] [LOG]   Connecting socket for: MMM-ATM
[11.01.2021 17:06.16.965] [LOG]   Starting node_helper for: MMM-ATM
[11.01.2021 17:06.16.965] [LOG]   Connecting socket for: newsfeed
[11.01.2021 17:06.16.966] [LOG]   Starting node helper for: newsfeed
[11.01.2021 17:06.16.967] [LOG]   Connecting socket for: MMM-MyScoreboard
[11.01.2021 17:06.16.968] [LOG]   Starting node_helper for module [MMM-MyScoreboard]
[11.01.2021 17:06.16.998] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'json-parse-async'
Require stack:
- /home/pi/MagicMirror/modules/MMM-MyScoreboard/providers/SNET.js
- /home/pi/MagicMirror/modules/MMM-MyScoreboard/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[11.01.2021 17:06.17.000] [LOG]   Loading module helpers ...
[11.01.2021 17:06.17.002] [LOG]   No helper found for module: alert.
[11.01.2021 17:06.17.003] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.17.003] [LOG]   Module helper loaded: updatenotification
[11.01.2021 17:06.17.004] [LOG]   No helper found for module: clock.
[11.01.2021 17:06.17.005] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.17.005] [LOG]   Module helper loaded: MMM-CalendarWeek
[11.01.2021 17:06.17.006] [LOG]   No helper found for module: compliments.
[11.01.2021 17:06.17.007] [LOG]   No helper found for module: weather.
[11.01.2021 17:06.17.008] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.17.009] [LOG]   Module helper loaded: MMM-ATM
[11.01.2021 17:06.17.010] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.17.011] [LOG]   Module helper loaded: newsfeed
[11.01.2021 17:06.17.012] [LOG]   Initializing new module helper ...
[11.01.2021 17:06.17.013] [LOG]   Module helper loaded: MMM-MyScoreboard
[11.01.2021 17:06.17.014] [LOG]   All module helpers loaded.
[11.01.2021 17:06.17.015] [LOG]   Starting server on port 8080 ...
[11.01.2021 17:06.17.018] [LOG]   Server started ...
[11.01.2021 17:06.17.019] [LOG]   Connecting socket for: updatenotification
[11.01.2021 17:06.17.020] [LOG]   Connecting socket for: MMM-CalendarWeek
[11.01.2021 17:06.17.020] [LOG]   Starting node helper for: MMM-CalendarWeek
[11.01.2021 17:06.17.021] [LOG]   Connecting socket for: MMM-ATM
[11.01.2021 17:06.17.021] [LOG]   Starting node_helper for: MMM-ATM
[11.01.2021 17:06.17.022] [LOG]   Connecting socket for: newsfeed
[11.01.2021 17:06.17.022] [LOG]   Starting node helper for: newsfeed
[11.01.2021 17:06.17.023] [LOG]   Connecting socket for: MMM-MyScoreboard
[11.01.2021 17:06.17.024] [LOG]   Starting node_helper for module [MMM-MyScoreboard]
[11.01.2021 17:06.17.026] [ERROR] App threw an error during load
[11.01.2021 17:06.17.033] [ERROR] Error: Cannot find module 'json-parse-async'
Require stack:
- /home/pi/MagicMirror/modules/MMM-MyScoreboard/providers/SNET.js
- /home/pi/MagicMirror/modules/MMM-MyScoreboard/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MyScoreboard/providers/SNET.js:48:19)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[11.01.2021 17:06.17.035] [ERROR] Whoops! There was an uncaught exception...
[11.01.2021 17:06.17.041] [ERROR] Error: Cannot find module 'json-parse-async'
Require stack:
- /home/pi/MagicMirror/modules/MMM-MyScoreboard/providers/SNET.js
- /home/pi/MagicMirror/modules/MMM-MyScoreboard/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-MyScoreboard/providers/SNET.js:48:19)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-MyScoreboard/providers/SNET.js',
    '/home/pi/MagicMirror/modules/MMM-MyScoreboard/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[11.01.2021 17:06.17.045] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[11.01.2021 17:06.17.046] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[11.01.2021 17:06.17.266] [ERROR] Whoops! There was an uncaught exception...
[11.01.2021 17:06.17.269] [ERROR] Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1300:14)
    at listenInCluster (net.js:1348:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1487:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
[11.01.2021 17:06.17.270] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[11.01.2021 17:06.17.271] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[11.01.2021 17:06.17.291] [LOG]   Launching application.
[11.01.2021 17:06.17.321] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Comment by BGvdS** [comment]
Solved it. I made a typo on the installation command, even when reinstalling.
