### ISSUE TITLE
No more posting since last update

### ISSUE THREAD

**Issue by 2hdlockness** [jclarke0000/MMM-MyScoreboard#70]
Hello
First of all Congratulations for your module that I have been using for a long time.
Unfortunately since the last update, nothing is displayed on my MM.
An npm start dev gives us:

MMM-MyScoreboard.js:365 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Class.boxScoreFactory (MMM-MyScoreboard.js:365:46)
    at MMM-MyScoreboard.js:550:31
    at Array.forEach (<anonymous>)
    at MMM-MyScoreboard.js:549:32
    at Array.forEach (<anonymous>)
    at Class.getDom (MMM-MyScoreboard.js:536:24)
    at main.js:113:35
    at new Promise (<anonymous>)
    at updateDom (main.js:111:10)
    at Object.updateDom (main.js:552:4)

My configuration file is defined like this:

{
      module: 'MMM-MyScoreboard',
      position: 'top_right',
      classes: 'default everyone',
      header: 'Résultats Football',
      config: {
        showLeagueSeparators: true,
        colored: true,
        viewStyle: 'oneLineWithLogos',
        sports: [
          {
            league: 'FRA_LIGUE_1'
          },
          {
            league: 'UEFA_CHAMPIONS'
          },
          {
            league: 'UEFA_EUROPA'
          },
          {
            league: 'UEFA_NATIONS'
          },
          {
            league: 'FRA_COUPE_DE_FRANCE'
          },
          {
            league: 'FRA_COUPE_DE_LA_LIGUE'
          },
          {
            league: 'FIFA_WORLD_CUP'
          },
          {
            league: 'FIFA_WORLD_CUP_Q_UEFA'
          },
          {
            league: 'UEFA_EUROPEAN_CHAMPIONSHIP'
          },	  
          {
            league: 'UEFA_EUROPEAN_CHAMPIONSHIP_Q'
          }
        ]
      }

I deleted the MMM-Myscoreboard directory then recloned it and finally run npm install but still nothing.
Hoping that you will be able to find a solution to my problem.
Best regard

**Comment by petter841206** [comment]
Same problem for me. To bad because this is the best module for MagicMirror in my opinion 😞

**Comment by DizzyDwarf0013** [comment]
I'm also having issues. Module just displays "Loading..."

**Comment by 2hdlockness** [comment]
After the update this afternoon everything works correctly again!

**Comment by DizzyDwarf0013** [comment]
I've tried deleting the directory, recloning, and installing, but no luck here. 
I do get "npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)" when I npm install.

**Comment by petter841206** [comment]
updated today but still no nuck

**Comment by dathbe** [comment]
Try my updated fork and let me know if you still have issues:
https://github.com/dathbe/MMM-MyScoreboard
